
name: CI

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Run 'yarn lint'
              run: |
                yarn install
                yarn lint
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Run 'yarn build'
              run: |
                yarn install
                yarn build
            - name: Upload executables
              uses: actions/upload-artifact@v2
              with:
                name: Distribution
                path: dist/*